sudo: required

language: java

services: 
  - docker

jdk:
  - oraclejdk8
  
env:
  - MONGODB_PORT=27017 RABBITMQ_AMQP_PORT=5672 RABBITMQ_WEB_PORT=15672 EIFFEL_ER_PORT=8084 JENKINS_PORT=8081 MAIL_SMTP_PORT=1025 MAIL_WEB_PORT=8025

before_install:
  - chmod +x pom.xml
  
script:
  - mvn test
